FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Gon.bf", "src\\Tests\\DefaultTests.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Variant.bf"]

[MainWindow]
X = 0
Y = 0
Width = 1180
Height = 885
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 400.0
RequestedHeight = 250.0
SizePriority = 250.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 302.0
RequestedHeight = 250.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 113.354
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1587.94
RequestedHeight = 150.0
SizePriority = 1587.94
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "DefaultTests.bf"
TabWidth = 115.0932
Type = "SourceViewPanel"
FilePath = "src\\Tests\\DefaultTests.bf"
CursorPos = 151
ProjectName = "lyb-gon"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Gon.bf"
TabWidth = 68.50932
Type = "SourceViewPanel"
FilePath = "src\\Gon.bf"
CursorPos = 1814
VertPos = 868.9335
ProjectName = "lyb-gon"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 1065.78
RequestedHeight = 269.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.6584
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 86.64597
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.95031
Type = "AutoWatchPanel"
Columns = [{Width = 322.0}, {Width = 322.0}, {Width = 322.0}]

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.4907
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.99379
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""
